code-insiders --install-extension antfu.icons-carbon --force
code-insiders --install-extension bradlc.vscode-tailwindcss --force
code-insiders --install-extension cschlosser.doxdocgen --force
code-insiders --install-extension Dart-Code.dart-code --force
code-insiders --install-extension Dart-Code.flutter --force
code-insiders --install-extension dbaeumer.vscode-eslint --force
code-insiders --install-extension ecmel.vscode-html-css --force
code-insiders --install-extension equinusocio.vsc-material-theme-icons --force
code-insiders --install-extension GitHub.copilot-nightly --force
code-insiders --install-extension jeff-hykin.better-cpp-syntax --force
code-insiders --install-extension LeonardSSH.vscord --force
code-insiders --install-extension ms-azuretools.vscode-docker --force
code-insiders --install-extension ms-vscode-remote.remote-containers --force
code-insiders --install-extension ms-vscode-remote.remote-wsl --force
code-insiders --install-extension ms-vscode.cmake-tools --force
code-insiders --install-extension ms-vscode.cpptools --force
code-insiders --install-extension ms-vscode.cpptools-extension-pack --force
code-insiders --install-extension ms-vscode.cpptools-themes --force
code-insiders --install-extension ms-vsliveshare.vsliveshare --force
code-insiders --install-extension ms-vsliveshare.vsliveshare-audio --force
code-insiders --install-extension ms-vsliveshare.vsliveshare-pack --force
code-insiders --install-extension PKief.material-icon-theme --force
code-insiders --install-extension rendinjast.amoled-black --force
code-insiders --install-extension twxs.cmake --force
code-insiders --install-extension undefined_publisher.quixotic --force
code-insiders --install-extension vscjava.vscode-gradle --force
code-insiders --install-extension wayou.vscode-todo-highlight --force
code-insiders --install-extension yinfei.luahelper --force
